<!--Thinsg need to be done
1)Style using the css
2)Mnimize the image by centering it and putting the paragraph next to it.
3)Add anything necessary-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Browse</title>
    <link rel ="stylesheet" href="./css/style.css">
    <script src="./css/style.css"></script>
</head>
<body>
    <header>
        <div class ="navbar">
        <a href="home.php">HOME</a>
        <a href="Browse.php">BROWSE</a>
        <a href="registration.php">MY REGISTRATION</a>
        <a href="search.php">SEARCH</a>
        <A href="myCollection.php">MY COLLECTION</A>
        <a href="login.php">LOGIN</a>
    </div>
</header>
<main>
    <!--This is the source for the image-->
    <img src ="./Images_for_library/home.jpg">
    <p><h2><strong>Welcome to the Student library</strong></h2>
        Our library is a free resource for all students, offering a vast collection of books across various genres, including fiction,
        non-fiction, science, history, technology, and more. Whether you're looking for academic materials, research resources, 
        or just a good book to read, you'll find it here!Students are welcome to borrow books, study in a quiet environment, 
        and collaborate with peers. Our mission is to support learning and knowledge-sharing, creating a space where everyone can thrive.
    <h3>Please register to use our services by clicking on the registration form or use the login if you are already registered, we really would love to have you as our customer </h3></p>
</main>
<!--This contains information about the privacy statements and Site map-->
    <footer>
        <ul>
        <li>Privacy statements</li>
        <li>Site map</li><!--Shows all the links to student library-->
        </ul>
        
    </footer>
</body>
</html>